export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

export const SEARCH_PRODUCTS_REQUEST = 'SERACH_PRODUCTS_REQUEST';
export const SEARCH_PRODUCTS_SUCCESS = 'SERACH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAIL = 'SERACH_PRODUCTS_FAIL';

export const FETCH_ONE_PRODUCT_REQUEST = 'FETCH_ONE_PRODUCT_REQUEST';
export const FETCH_ONE_PRODUCT_FAIL = 'FETCH_ONE_PRODUCT_FAIL';
export const FETCH_ONE_PRODUCT_SUCCESS = 'FETCH_ONE_PRODUCT_SUCCESS';

export const FETCH_PRODUCT_OPTIONS_REQUEST = 'FETCH_PRODUCT_OPTIONS_REQUEST';
export const FETCH_PRODUCT_OPTIONS_FAIL = 'FETCH_PRODUCT_OPTIONS_FAIL';
export const FETCH_PRODUCT_OPTIONS_SUCCESS = 'FETCH_PRODUCT_OPTIONS_SUCCESS';

export const GET_PRODUCT = 'GET_PRODUCT';

export const NOTIFICATION_SHOW = 'NOTIFICATION_SHOW';
export const NOTIFICATION_HIDE = 'NOTIFICATION_HIDE';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';

export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const FETCH_ORDER_DETAIL_REQUEST = 'FETCH_ORDER_DETAIL_REQUEST';
export const FETCH_ORDER_DETAIL_SUCCESS = 'FETCH_ORDER_DETAIL_SUCCESS';
export const FETCH_ORDER_DETAIL_FAIL = 'FETCH_ORDER_DETAIL_FAIL';

export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_RESET_STATE = 'AUTH_RESET_STATE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REGESTRATION_SUCCESS = 'AUTH_REGESTRATION_SUCCESS';

export const FLASH_SHOW = 'FLASH_SHOW';
export const FLASH_HIDE = 'FLASH_HIDE';

export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_HIDE = 'MODAL_HIDE';

export const NEXT_CATEGORY = 'NEXT_CATEGORY';
export const PREV_CATEGORY = 'PREV_CATEGORY';

export const CART_REQUEST = 'CART_REQUEST';
export const CART_SUCCESS = 'CART_SUCCESS';
export const CART_FAIL = 'CART_FAIL';

export const CART_CHANGE_REQUEST = 'CART_CHANGE_REQUEST';
export const CART_CHANGE_SUCCESS = 'CART_CHANGE_SUCCESS';
export const CART_CHANGE_FAIL = 'CART_CHANGE_FAIL';

export const SHIPPING_REQUEST = 'SHIPPING_REQUEST';
export const SHIPPING_SUCCESS = 'SHIPPING_SUCCESS';
export const SHIPPING_FAIL = 'SHIPPING_FAIL';

export const BILLING_REQUEST = 'BILLING_REQUEST';
export const BILLING_SUCCESS = 'BILLING_SUCCESS';
export const BILLING_FAIL = 'BILLING_FAIL';

export const CART_CLEAR_REQUEST = 'CART_CLEAR_REQUEST';
export const CART_CLEAR_SUCCESS = 'CART_CLEAR_SUCCESS';
export const CART_CLEAR_FAIL = 'CART_CLEAR_FAIL';

export const CART_REMOVE_REQUEST = 'CART_REMOVE_REQUEST';
export const CART_REMOVE_SUCCESS = 'CART_REMOVE_SUCCESS';
export const CART_REMOVE_FAIL = 'CART_REMOVE_FAIL';

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';

export const CART_CONTENT_REQUEST = 'CART_CONTENT_REQUEST';
export const CART_CONTENT_SUCCESS = 'CART_CONTENT_SUCCESS';
export const CART_CONTENT_FAIL = 'CART_CONTENT_FAIL';
export const CART_CONTENT_SAVE = 'CART_CONTENT_SAVE';

export const CHANGE_AMOUNT = 'CHANGE_AMOUNT';

export const FETCH_PAGES_REQUEST = 'FETCH_PAGES_REQUEST';
export const FETCH_PAGES_SUCCESS = 'FETCH_PAGES_SUCCESS';
export const FETCH_PAGES_FAIL = 'FETCH_PAGES_FAIL';

export const PAYPAL_SETTLEMENTS_REQUEST = 'PAYPAL_SETTLEMENTS_REQUEST';
export const PAYPAL_SETTLEMENTS_SUCCESS = 'PAYPAL_SETTLEMENTS_SUCCESS';
export const PAYPAL_SETTLEMENTS_FAIL = 'PAYPAL_SETTLEMENTS_FAIL';
